# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 363)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_add.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_upd = QtWidgets.QPushButton(Form)
        self.btn_upd.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_upd.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_upd.setObjectName("btn_upd")
        self.horizontalLayout.addWidget(self.btn_upd)
        self.btn_del = QtWidgets.QPushButton(Form)
        self.btn_del.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_del.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_del.setObjectName("btn_del")
        self.horizontalLayout.addWidget(self.btn_del)
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.text = QtWidgets.QLabel(Form)
        self.text.setText("")
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Кофе"))
        self.btn_add.setText(_translate("Form", "Добавить"))
        self.btn_upd.setText(_translate("Form", "Изменить"))
        self.btn_del.setText(_translate("Form", "Удалить"))
